language: generic
osx_image: xcode8.3
os: osx

before_install:
  - brew tap osrf/ros2
  - brew tap ros/deps
#  - brew unlink numpy
  - brew install python3 wget cppcheck gtest tinyxml eigen pcre # cmake already installed
  - brew install asio tinyxml2
  - brew tap homebrew/science
#  - brew install opencv --without-python
  - sudo -H python3 -m pip install empy setuptools nose vcstool pep8 pydocstyle pyflakes flake8 mock coverage
  - gem install xcpretty
  - mkdir -p ~/ament_ws/src
  - mkdir -p ~/ament_ws/src
  - cd ~/ament_ws
  - wget https://raw.githubusercontent.com/esteve/ament_java/master/ament_java.repos
  - vcs import ~/ament_ws/src < ament_java.repos
  - src/ament/ament_tools/scripts/ament.py build --parallel --symlink-install --isolated
  - mkdir -p ~/ros2_java_ws/src
  - cd ~/ros2_java_ws
  - wget https://raw.githubusercontent.com/esteve/ros2_java/master/ros2_java_desktop_travis.repos
  - vcs import ~/ros2_java_ws/src < ros2_java_desktop_travis.repos
  - cd ~/ros2_java_ws/src/ros2/rosidl_typesupport
  - patch -p1 < ../../ros2_java/ros2_java/rosidl_typesupport_ros2_java.patch

script:
  - /bin/pwd
  - cd ~/ros2_java_ws && . ~/ament_ws/install_isolated/local_setup.sh && ament build --parallel --symlink-install --isolated && ament test --symlink-install --isolated --only-packages ament_cmake_export_jars rcljava rcljava_common rosidl_generator_java
